In [1]:
import numpy as np 
import pandas as pd 

In [2]:
df = pd. DataFrame({'text': [ 'people watch football'
, 'football watch football', 'people write comment', 'football write comment'], 'output': [1,1,0,0]})
df

text  output
0    people watch football       1
1  football watch football       1
2     people write comment       0
3   football write comment       0

### Bag of Words

`https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html` it has tokenizer, stop_word, many useful hyperparameters

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
# vocabulary
cv.vocabulary_
# {'word':index position}

{'people': 2, 'watch': 3, 'football': 1, 'write': 4, 'comment': 0}

In [6]:
bow[0].toarray() # people watch football

array([[0, 1, 1, 1, 0]])

In [7]:
cv.transform(['football watch and write commment of football']).toarray()
# since and & of were the words which were not represented in the training
# therefore they were not shown in numeric representation

# anyways `and, of` are stopwords which will be removed in your pre-processing step

array([[0, 2, 0, 1, 1]])

### N-grams

In [8]:
df

text  output
0    people watch football       1
1  football watch football       1
2     people write comment       0
3   football write comment       0

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2)) # Bi-gram

In [10]:
bow = cv.fit_transform(df['text'])

In [11]:
# vocabular
print(cv.vocabulary_)

{'people watch': 2, 'watch football': 4, 'football watch': 0, 'people write': 3, 'write comment': 5, 'football write': 1}


In [16]:
cv = CountVectorizer(ngram_range=(1,2)) # Unigram as well a bigram
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)

#(1,3) -> uni + bi + tri Grams 

{'people': 4, 'watch': 7, 'football': 1, 'people watch': 5, 'watch football': 8, 'football watch': 2, 'write': 9, 'comment': 0, 'people write': 6, 'write comment': 10, 'football write': 3}


### TF-IDF

In [13]:
df

text  output
0    people watch football       1
1  football watch football       1
2     people write comment       0
3   football write comment       0

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [17]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
['comment' 'football' 'people' 'watch' 'write']
