#### Word2Vec (pre-trained) using Gensim Library 

In [1]:
#%pip install scipy==1.12 
#The scipy.linalg functions tri, triu & tril are deprecated and will be removed in SciPy 1.13.
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [2]:
#%pip install wget
#brew install wget >> on mac

# !wget -c "https://s3.amazonaws.com/ dl4j-distribution/GoogleNews-vectors-negative300.bin.gz" # not working


In [3]:
import gensim.downloader as api

# Load the smaller version of  the word2vec model
model = api.load('glove-twitter-25')

# wv = api.load('word2vec-google-news-300')

vec_king = model['cricket']
print(vec_king)

model.most_similar('facebook')


[ 0.48169  -0.066325 -0.44454  -1.7274   -1.0247   -0.78493   0.50351
 -0.65595   0.56451  -0.03321  -0.14383   0.71937  -2.8215    0.86131
  0.79783  -0.49762   0.044193 -0.24435   0.051926  1.0575   -1.1741
  0.84042   0.35934  -1.0306   -0.69021 ]


[('twitter', 0.9480050802230835),
 ('google', 0.923143208026886),
 ('instagram', 0.9184154272079468),
 ('internet', 0.9143877029418945),
 ('youtube', 0.9113808274269104),
 ('tumblr', 0.9077149033546448),
 ('link', 0.8995786905288696),
 ('fb', 0.8734270334243774),
 ('post', 0.8671452403068542),
 ('site', 0.8642723560333252)]

In [4]:
model.similarity('man','python')

0.29540685

In [5]:
model.doesnt_match(['python','java','choclate'])

'choclate'

In [6]:
vec = model['king'] - model['man'] + model['women']
model.most_similar([vec])

[('women', 0.813094973564148),
 ('heritage', 0.8079677820205688),
 ('african', 0.8042827248573303),
 ('rogue', 0.8038854598999023),
 ('native', 0.8007871508598328),
 ('navy', 0.7999263405799866),
 ('authentic', 0.7965380549430847),
 ('republic', 0.7925301790237427),
 ('army', 0.7922316193580627),
 ('urban', 0.7909184694290161)]

In [7]:
vec = model[ 'inr'] - model['england']
model. most_similar([vec])

[('ﾌﾟｰ', 0.873827338218689),
 ('ぶーっ', 0.845775842666626),
 ('万円分をクイズ毎に毎日', 0.8378826975822449),
 ('描いてよ', 0.8318928480148315),
 ('ｽﾘ', 0.8256760835647583),
 ('ヵ', 0.8214247822761536),
 ('じゃじゃじゃじゃーん', 0.8155319094657898),
 ('一人が好きだが独りは寂しいn', 0.8150526285171509),
 ('暇だよー', 0.8146540522575378),
 ('ｳﾜｧｧｧﾝ', 0.8106462359428406)]

### Training own word2vec model

* Dataset : https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books


In [8]:
import pandas as pd 
import numpy as np 
#%pip install gensim

In [9]:
import gensim
import os 

In [10]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import codecs

story = []
for filename in os.listdir('data/GOT word2vec model'):
    file_path = os.path.join('data/GOT word2vec model', filename)
    with codecs.open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        corpus = f.read()
        raw_sent = sent_tokenize(corpus)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))

In [11]:
len(story)

158874

In [12]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    workers = 2, # default -> no of cores in cpu
    vector_size=100 # default -> size of your vector
)

In [13]:
model.build_vocab(story)

In [14]:
model.train(story, total_examples=model.corpus_count,epochs=model.epochs)#default is model.epoch = 10 epochs

(6574300, 8625265)

In [15]:
model.wv.most_similar('arya')

[('sansa', 0.8622716665267944),
 ('brienne', 0.835281491279602),
 ('she', 0.8075915575027466),
 ('gendry', 0.7892709374427795),
 ('dany', 0.7715105414390564),
 ('bran', 0.7594992518424988),
 ('gilly', 0.7518959641456604),
 ('catelyn', 0.7436895370483398),
 ('meera', 0.7410670518875122),
 ('jojen', 0.676540732383728)]

In [16]:
model.wv.doesnt_match(['jon','arya','sansa','bran','robb'])

'jon'

In [17]:
model.wv['king']

array([ 1.5499022 , -0.6303899 ,  0.34399587, -0.32847127, -1.5742117 ,
        3.1262279 ,  0.53704846, -3.5951672 ,  1.4394473 ,  2.089483  ,
       -1.311755  ,  3.4387891 ,  0.6388481 ,  0.14805694, -1.7133799 ,
       -0.8210902 ,  0.8057059 , -1.7568965 , -3.636463  , -1.5458529 ,
        2.4595778 ,  1.9654403 , -0.13458323, -1.2813189 ,  0.89656836,
       -0.8697923 , -1.860649  , -1.3238059 , -0.39947876,  2.6886177 ,
        0.03934034, -0.1703846 , -2.252762  , -1.7590394 ,  1.5081266 ,
        2.6120377 ,  1.2349254 , -1.628152  , -1.2542586 ,  0.97409123,
        0.62794983, -1.7277275 ,  0.6022737 ,  2.5097854 ,  0.6782411 ,
       -0.6106981 , -1.3115643 , -0.7744812 ,  2.2014363 , -2.282704  ,
       -0.3313563 ,  1.8185629 ,  1.9934523 , -1.3923737 ,  0.281104  ,
       -2.0670986 , -0.58392924,  1.4699812 , -0.14376333, -0.6449009 ,
        2.3097396 , -0.2051894 , -1.2018874 ,  1.8512411 , -0.97389007,
       -0.515533  ,  1.0543554 ,  0.47939986, -3.5530884 , -0.20

In [18]:
model.wv.similarity('arya','sansa')

0.8622717

In [19]:
model.wv.get_normed_vectors()
# vector of all the corpus at once in 100 dim

array([[-0.00851243, -0.05727293,  0.03543206, ..., -0.19520545,
        -0.00033079,  0.16044116],
       [ 0.07716834,  0.0780279 ,  0.00061345, ..., -0.09756875,
        -0.08356271,  0.28234667],
       [-0.01712857,  0.00273303, -0.05542555, ..., -0.10546146,
         0.05981426, -0.18779626],
       ...,
       [-0.00542257, -0.08765634,  0.14108725, ..., -0.18448909,
        -0.09964444, -0.03394092],
       [ 0.08428675,  0.09782634,  0.15397133, ..., -0.11279684,
         0.03009402,  0.03401096],
       [ 0.11142337,  0.0957833 ,  0.09305785, ..., -0.04265475,
        -0.14737272,  0.04741646]], dtype=float32)

In [20]:
model.wv.get_normed_vectors().shape

(17869, 100)

In [21]:
y = model.wv.index_to_key
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'them',
 'lord',
 'no',
 'from',
 'were',
 'would',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'could',
 'are',
 'we',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'king',
 'who',
 'well',
 'down',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'old',
 'hand',
 'even',
 'too',
 'before',
 'never',
 'tyrion',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'father',
 'now',
 'eyes',
 'black',
 'told',
 'thought',
 'lady',
 'time',
 'then',
 'how',
 'long',
 'has',
 'might',
 'us',
 'come',
 'where',
 'here',
 'can',
 'through',
 'still',
 'face',
 'head',
 'red',
 'way',
 'page',
 'boy',
 'must',
 'once',
 'good',
 'two',
 'over',
 'little',
 'about',
 'brother'

In [22]:
len(y)

17869

In [23]:
# since cannot visualize 100 vector 
# therefore applying PCA as dimension reductionality

In [24]:
from sklearn.decomposition import PCA 
pca = PCA(n_components=3)

In [25]:
X = pca.fit_transform(model.wv.get_normed_vectors())
X[:2]

array([[-0.22985749,  0.5833741 , -0.03147787],
       [-0.20773856,  0.34001124,  0.06630613]], dtype=float32)

In [26]:
X

array([[-0.22985749,  0.5833741 , -0.03147787],
       [-0.20773856,  0.34001124,  0.06630613],
       [ 0.2645627 ,  0.5806878 ,  0.21485174],
       ...,
       [ 0.16234173,  0.29044664, -0.24864079],
       [-0.10635922, -0.19495127, -0.09795916],
       [ 0.29938197, -0.2587119 , -0.0751387 ]], dtype=float32)

In [27]:

import plotly.express as px



# Now you can create and show the Plotly figure
fig = px.scatter_3d(X[:100], x=0, y=1,z=2, color=y[:100])
fig.show()


In [28]:
%pip install nbformat==4.2.0

  Using cached nbformat-4.2.0-py2.py3-none-any.whl.metadata (1.1 kB)
Using cached nbformat-4.2.0-py2.py3-none-any.whl (153 kB)
  Attempting uninstall: nbformat
    Found existing installation: nbformat 5.10.4
    Uninstalling nbformat-5.10.4:
      Successfully uninstalled nbformat-5.10.4
Note: you may need to restart the kernel to use updated packages.
